#+title:        Introduction
#+macro:        ews /Emacs Writing Studio/
#+startup:      content

Negli ultimi cinquemila anni, la scrittura é passata dalla argilla alla
cesellattura nella pietra alla carta, computer, e, più di recente,
l'intelligenza artificiale. Prima dell'avvento della scrittura elettronica,
tutti gli autori necessitano di un notebook, una penna, e macchina da
scrivere. Essere uno scrittore nell'era digitale, per molti versi, é più
complicato che nell'era della argilla, pietra o carta.

Gli scrittori contemporanei sono spesso sopraffatti da una moltitudine di
strumenti elettronici, ogniuno serve una specifica funzione. L'informazione
é sparpagliata su diverse piattaforme e salvata in formati incompatibili,
portando ad un processo di scrittura complesso e dispendioso in termini di
tempo. Il solievo per questa complessità é uno dei principali vantaggi di
Emacs.

Sfortunatamente, il precedente paragrafo descrive come molti studenti,
autori, ricercatori e altri scrittori gestiscono il loro modo di flusso di
lavoro. Cosa succederebbe se fosse possibile fare le cose in modo diverso e
utilizzare lo stesso programma per creare opere scritte dall'ideazione alla
pubblicazione? Questo libro introduce Emacs, un potente strumento che può
assiterti con ogni cosa dalla scintilla iniziale della tua idea fino alla
pubblicazione del tuo articolo finale, libro o sito web. Emacs ti libera
dalla fatica di destreggiarti tra i software e concetrarti sulla scrittura.


Questo libro é per scrittori che vogliono la liberta di rompere le
costrizzioni degli strumenti convenzionali di scrittura ed abbracciare un
ambiente più flessibile, potente e personalizzabile. Che tu sia uno
scrittore che tesse intricate storie di fantasia o un ricercatore che crea
testi di saggistica dettagliati, {{{ews}}} (EWS) offre una guida
omnicomprensiva per trasformare il tuo processo di scrittura.

* Fiction writers
Come scrittore di narrativa, la tua immaginazione é la tua più importante
risorsa. Hai bisogno di uno strumento che possa tenere il passo con la
fluidità delle tue idee, che ti permetta di concentrarti sulla creazione di
personaggi ricchi, trame intricate e mondi vividi senza distrazioni. Con
Emacs, puoi mantenere note organizzate, bozze e schizzi di personaggi
all'interno di un unico ambiente.

La potenti funzioni di ricerca e sostituzione, combinato con modelli
personalizzabili, ti permettono di gestire facilmente la coerenza dei nomi
nei personaggi, luoghi e altri dettagli critici all'interno del tuo
manoscritto. Quando l'ispirazione colpisce, l'interfaccia minimale di Emacs
ti permette di tuffarti dritto nella scrittura senza distrazioni da
elementi grafici non necessari.

Neal Town Stephenson, uno scrittore Americano conosciuto per le sua
fantascienza speculativa, si riferisce ad Emcas come a un word processor
termonucleare, no, non in un modo che distruga la scrittura in una palla di
fuoco, ma nel suo immenso potere rispetto agli strumenti di scrittura convenzionali.

* Non-fiction writers
Non-fiction writing demands precision, organisation, and meticulous research. Whether you're working on a dissertation, a technical report, or a historical biography, Emacs provides you with the tools to effectively manage vast amounts of data. You can efficiently structure your research notes, manage bibliographies, and outline your work.

Emacs allows you to seamlessly integrate these elements into your writing, ensuring that all your research is at your fingertips as you draft your work. The ability to export your manuscript to various formats, such as PDF or HTML, ensures that your work is ready for publication or sharing with peers without the hassle of format conversions.

* Multitasking writers
In today's fast-paced world, many writers manage multiple projects simultaneously. Emacs is the perfect tool for managing a diverse writing portfolio.

You can effortlessly switch between different projects, be it a short story, a research paper, or even your daily journal. Emacs' powerful task management features help you keep track of deadlines and tasks and track progress across all your writing endeavours.

* Distracted writers
If you find yourself easily distracted by the features of modern writing software, Emacs offers a refreshing change. With its focus on plain text and keyboard-driven commands, Emacs provides a genuinely distraction-free environment where the only thing that matters is your words, allowing you to focus on your writing without interruptions.

Writing in Emacs brings you back to the days when the typewriter stood between the writer and the written words. But Emacs also has powerful editing capabilities, so there is no need for correction fluid.

* Curious writers
Finally, this book is for those who are not just looking for a tool but for an opportunity to learn and grow as technology users. Emacs is not just software; it is a way of life. As you learn to use its powerful features, you develop new skills that enhance your writing process and overall productivity, inspiring you to explore new possibilities in your writing journey.

Emacs was initially conceived for software developers, but you don't need to be a computer wiz to use it as an author. This book flattens the steep learning curve, helping you unlock the full potential of Emacs as your ultimate writing companion.
